### ISSUE TITLE
Error: Unable to find matching architecture with vendored_frameworks in pod

### ISSUE THREAD

**Issue by canhth** [keith/ld64.lld#3]
Hi Keith,
I got this error when trying to build my project. The issue coming from `vendored_frameworks`.
```
ld64.lld: error: unable to find matching architecture in 
/Users/canhtran/my-project/Pods/../Modules/KYCModule/Frameworks/FaceLiveDetect.framework/FaceLiveDetect
```
Is there any trick to by-pass or fix it?

**Comment by keith** [comment]
What's the output of running `file path/to/binary` and what arch / platform are you linking for? Does it link with the default linker?

**Comment by canhth** [comment]
The output of running file `path/to/binary`:

```
/Users/canhtran/.../FaceIDLiveDetect: Mach-O universal binary with 2 architectures: [arm64:current ar archive current ar archive] [arm_v7]
/Users/canhtran/.../FaceIDLiveDetect (for architecture arm64):	current ar archive
/Users/canhtran/.../FaceIDLiveDetect (for architecture armv7):	current ar archive
```

I'm adding those .framework via Podspec:
`s.ios.vendored_frameworks = 'FaceLiveDetect/Frameworks/*.framework'

- Build Active Architecture Only: YES
- Excluded Arch: arm64

**Comment by keith** [comment]
it looks like that framework is probably built for device, are you trying to build for the arm64 simulator? (in which case you'd likely need a xcframework)

you can inspect the framework's platforms with `vtool -show path/to/binary`

**Comment by canhth** [comment]
@keith I think you're right, that framework is used for Camera and Liveness detection. 
But my project compiles success with normal build. Only got this error when trying with `llvm`

Result of running: `vtool -show path/to/binary`
``` file #0 for cputype (16777228, 0) is not mach-o```

I checked the static frameworks in my App's binary using linked_map, the `FaceLiveDetect` is there.
Not sure what exactly I missed.

**Comment by keith** [comment]
hrm maybe you have to use `lipo` to extract the slice first in this case? I'm not sure if that error is a red herring or not. But does it link with the default linker? It's possible lld has different behavior here but if it didn't link with the default linker that would be good to know too

**Comment by canhth** [comment]
It's linked with the default linker.
I've created a simple demo here: [DemoLLVM.zip](https://github.com/keith/ld64.lld/files/10388293/DemoLLVM.zip)
Added in Other Linker Flags: `-fuse-ld=/Users/canhtran/clang-llvm/bin/ld64.lld`

Could you please help to take a look? 🙏

**Comment by keith** [comment]
Looks like ld64 hints at the issue:

```
ld: warning: ignoring file /Users/ksmiley/Downloads/DemoLLVM/Frameworks/MGFaceIDBaseKit.framework/MGFaceIDBaseKit, file is universal (armv7,arm64) but does not contain the x86_64 architecture: /Users/ksmiley/Downloads/DemoLLVM/Frameworks/MGFaceIDBaseKit.framework/MGFaceIDBaseKit
ld: warning: ignoring file /Users/ksmiley/Downloads/DemoLLVM/Frameworks/MGFaceIDLiveDetect.framework/MGFaceIDLiveDetect, file is universal (armv7,arm64) but does not contain the x86_64 architecture: /Users/ksmiley/Downloads/DemoLLVM/Frameworks/MGFaceIDLiveDetect.framework/MGFaceIDLiveDetect
```

It is just ignoring them where lld is erroring. I can look into making lld ignore them in this case as well, but that just means you're not actually relying on these at least in this configuration and you should remove them from the dependencies.

Like we expected it is because they are device only frameworks:

```
otool -l MGFaceIDLiveDetect | grep LC_VERS | sort -u
      cmd LC_VERSION_MIN_IPHONEOS
```

So if you need it to work on the simulator you'll need a different binary, if you don't then you should exclude those from the link until it's fixed in lld

**Comment by keith** [comment]
I submitted a patch for this here: https://reviews.llvm.org/D141638 but there might be some push back since this case is pretty rare and likely a misconfiguration in your build. Feel free to follow along there for the potential resolution!
